baseURL = "https://kasprowicz.pro/"
languageCode = "pl"

theme = "ananke"
title = "Kasprowicz, obviously."
copyright = "Olgierd Kasprowicz"

paginate = 5 # Number of posts to show before paginating

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
enableGitInfo = true

[params]
show_reading_time = true
logo_text = "btw that was Olgierd"
rss="/index.xml"

[menu]
  [[menu.main]]
    name = "3rd party"
    url = "/3party"
    weight = 40

  [[menu.main]]
    name = "Now"
    url = "/now"
    weight = 20

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 10

[markup.goldmark.renderer]
unsafe= true
