baseURL = "https://kasprowicz.pro/"
languageCode = "pl"

title = "Hi, I'm Olgierd"

theme = "ananke"

[menu]

  [[menu.main]]
    name = "github"
    url = "https://github.com/allgreed/"
    weight = -110

  [[menu.main]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/olgierdkasprowicz"
    weight = -100
