baseURL = "https://kasprowicz.pro/"
languageCode = "pl"

title = "Hi, I'm Olgierd"

paginate = 5 # Number of posts to show before paginating

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[menu]

  [[menu.main]]
    name = "github"
    url = "https://github.com/allgreed/"
    weight = -110

  [[menu.main]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/olgierdkasprowicz"
    weight = -100
