baseURL = "https://kasprowicz.pro/"
languageCode = "pl"

theme = "ananke"
title = "Kasprowicz, obviously."
copyright = "Olgierd Kasprowicz"

paginate = 5 # Number of posts to show before paginating

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
enableGitInfo = true

[params]
show_reading_time = true
logo_text = "btw that was Olgierd"

[menu]
  [[menu.main]]
    name = "Github"
    url = "https://github.com/allgreed/"
    weight = -110

  [[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/olgierdkasprowicz"
    weight = -100

  [[menu.main]]
    name = "Toptal"
    url = "https://www.toptal.com/resume/olgierd-kasprowicz"
    weight = -90

  [[menu.main]]
    name = "3rd party"
    url = "/3party"
    weight = 10

[markup.goldmark.renderer]
unsafe= true
